/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bpd.arsip.view.panel;

import java.awt.event.ActionListener;

/**
 *
 * @author Dany
 */
public class PanelMenuUser extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuUser
     */
    public PanelMenuUser() {
        initComponents();
    }
    
    
    public void addListenerMenuTransaksiUser(ActionListener listener) {
        transaksi.addActionListener(listener);
    }

    public void addListenerMenuPencarianUser(ActionListener listener) {
        pencarian.addActionListener(listener);
    }
    
    public void addListenerMenuPengaturanUser(ActionListener listener) {
        pengaturan.addActionListener(listener);
    }
    
    public void addListenerMenuLaporanUser(ActionListener listener) {
        laporan.addActionListener(listener);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        transaksi = new dany.swing.lib.button.ButtonIconGlass();
        laporan = new dany.swing.lib.button.ButtonIconGlass();
        pencarian = new dany.swing.lib.button.ButtonIconGlass();
        pengaturan = new dany.swing.lib.button.ButtonIconGlass();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        transaksi.setText("Transaksi");
        transaksi.setIconReflection(new javax.swing.ImageIcon(getClass().getResource("/com/bpd/arsip/icon/Transaksi.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 116, 0, 0);
        add(transaksi, gridBagConstraints);

        laporan.setText("Laporan");
        laporan.setIconReflection(new javax.swing.ImageIcon(getClass().getResource("/com/bpd/arsip/icon/publish (1).png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 175, 0, 125);
        add(laporan, gridBagConstraints);

        pencarian.setText("Pencarian");
        pencarian.setIconReflection(new javax.swing.ImageIcon(getClass().getResource("/com/bpd/arsip/icon/cari.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 116, 33, 0);
        add(pencarian, gridBagConstraints);

        pengaturan.setText("Pengaturan");
        pengaturan.setIconReflection(new javax.swing.ImageIcon(getClass().getResource("/com/bpd/arsip/icon/Settings.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 175, 33, 125);
        add(pengaturan, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dany.swing.lib.button.ButtonIconGlass laporan;
    private dany.swing.lib.button.ButtonIconGlass pencarian;
    private dany.swing.lib.button.ButtonIconGlass pengaturan;
    private dany.swing.lib.button.ButtonIconGlass transaksi;
    // End of variables declaration//GEN-END:variables
}
