/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bpd.arsip.view.panel;

import com.bpd.arsip.controller.PenyesuaianBerkasController;
import com.bpd.arsip.model.DebiturModel;
import com.bpd.arsip.model.PengarsipanModel;
import com.bpd.arsip.view.MainFrame;
import com.stripbandunk.jwidget.JDynamicTable;
import com.stripbandunk.jwidget.JPagination;
import com.stripbandunk.jwidget.model.DynamicTableModel;
import javax.swing.JTextField;

/**
 *
 * @author Dany Candra
 */
public class PanelPenyesuaianBerkas extends javax.swing.JPanel {

    private final PengarsipanModel pengarsipanModel;
    private final DebiturModel debiturModel;
    private final DynamicTableModel<PengarsipanModel> tableModel;
    private final DynamicTableModel<DebiturModel> tableModelDebitur;
    private final PenyesuaianBerkasController controller;
    private MainFrame mainFrame;
    private final int PAGE_SIZE = 20;

    /**
     * Creates new form PanelInstansi
     */
    public PanelPenyesuaianBerkas() {
        pengarsipanModel = new PengarsipanModel();
        debiturModel = new DebiturModel();
        controller = new PenyesuaianBerkasController();
        controller.setPengarsipanModel(pengarsipanModel);
        controller.setDebiturModel(debiturModel);

        tableModelDebitur = new DynamicTableModel<>(DebiturModel.class);

        tableModel = new DynamicTableModel<>(PengarsipanModel.class);
        tableModel.setGroup("ttpengembalian");

        initComponents();

        tablePengembalianBerkas.setDynamicModel(tableModel);

    }

    public MainFrame getMainFrame() {
        return mainFrame;
    }

    public void setMainFrame(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
    }

    public DynamicTableModel<DebiturModel> getTableModelDebitur() {
        return tableModelDebitur;
    }

    public DynamicTableModel<PengarsipanModel> getTableModel() {
        return tableModel;
    }

    public JDynamicTable getTablePengembalianBerkas() {
        return tablePengembalianBerkas;
    }

    public JPagination getjPagination() {
        return jPagination;
    }

    public JTextField getTextCIF() {
        return textCIF;
    }

    public void loadTable() {
        controller.reload(PAGE_SIZE, this);
        tableModelDebitur.clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPortTransparan1 = new com.bpd.arsip.component.ViewPortTransparan();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePengembalianBerkas = new com.stripbandunk.jwidget.JDynamicTable();
        jPagination = new com.stripbandunk.jwidget.JPagination();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textCIF = new javax.swing.JTextField();
        buttonCek = new javax.swing.JButton();
        buttonTandaTerima = new javax.swing.JButton();

        viewPortTransparan1.setView(tablePengembalianBerkas);

        setOpaque(false);

        jScrollPane1.setViewport(viewPortTransparan1);

        tablePengembalianBerkas.setForeground(new java.awt.Color(255, 255, 255));
        tablePengembalianBerkas.setOpaque(false);
        jScrollPane1.setViewportView(tablePengembalianBerkas);

        jPagination.setOpaque(false);
        jPagination.addPaginationListener(new com.stripbandunk.jwidget.listener.PaginationListener() {
            public void onPageChange(com.stripbandunk.jwidget.event.PaginationEvent evt) {
                jPaginationOnPageChange(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Pencarian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MASUKAN CIF");

        textCIF.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        textCIF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textCIFKeyReleased(evt);
            }
        });

        buttonCek.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonCek.setText("Cek");
        buttonCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(textCIF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCek)
                .addGap(4, 4, 4))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCIF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCek, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonTandaTerima.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonTandaTerima.setText("Pindah Dus");
        buttonTandaTerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTandaTerimaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPagination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonTandaTerima)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPagination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTandaTerima, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textCIFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCIFKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            controller.search(textCIF.getText(), this);
        }
    }//GEN-LAST:event_textCIFKeyReleased

    private void jPaginationOnPageChange(com.stripbandunk.jwidget.event.PaginationEvent evt) {//GEN-FIRST:event_jPaginationOnPageChange
        // TODO add your handling code here:
        final int skip = (evt.getCurrentPage() - 1) * evt.getPageSize();
        final int max = evt.getPageSize();
        controller.onPageChange(skip, max, this);
    }//GEN-LAST:event_jPaginationOnPageChange

    private void buttonCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCekActionPerformed
        // TODO add your handling code here:
        controller.search(textCIF.getText(), this);

    }//GEN-LAST:event_buttonCekActionPerformed

    private void buttonTandaTerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTandaTerimaActionPerformed
        // TODO add your handling code here:
        controller.selectDebitur(this);
        loadTable();
    }//GEN-LAST:event_buttonTandaTerimaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCek;
    private javax.swing.JButton buttonTandaTerima;
    private javax.swing.JLabel jLabel2;
    private com.stripbandunk.jwidget.JPagination jPagination;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.stripbandunk.jwidget.JDynamicTable tablePengembalianBerkas;
    private javax.swing.JTextField textCIF;
    private com.bpd.arsip.component.ViewPortTransparan viewPortTransparan1;
    // End of variables declaration//GEN-END:variables
}
