/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bpd.arsip.view.panel;

import java.awt.event.ActionListener;

/**
 *
 * @author Dany
 */
public class PanelMenuLaporan extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuTransaksi
     */
    public PanelMenuLaporan() {
        initComponents();
    }
    
    public void addListenerMenuLaporanCis(ActionListener listener) {
        laporanCis.addActionListener(listener);
    }
    
    public void addListenerMenuLaporanIsiDus(ActionListener listener) {
        laporanIsiDus.addActionListener(listener);
    }
    
    public void addListenerMenuLaporanPenerimaan(ActionListener listener) {
        laporanPenerimaanBerkas.addActionListener(listener);
    }
    
    public void addListenerMenuLaporanPengembalian(ActionListener listener) {
        laporanPengembalianBerkas.addActionListener(listener);
    }
    
    public void addListenerMenuLaporanOpname(ActionListener listener) {
        laporanOpname.addActionListener(listener);
    }
    
    public void addListenerMenuLaporanJatuhTempo(ActionListener listener) {
        laporanJatuhTempo.addActionListener(listener);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        laporanCis = new dany.swing.lib.button.ButtonIconGlass();
        laporanPengembalianBerkas = new dany.swing.lib.button.ButtonIconGlass();
        laporanOpname = new dany.swing.lib.button.ButtonIconGlass();
        laporanIsiDus = new dany.swing.lib.button.ButtonIconGlass();
        laporanJatuhTempo = new dany.swing.lib.button.ButtonIconGlass();
        laporanPenerimaanBerkas = new dany.swing.lib.button.ButtonIconGlass();

        setBackground(new java.awt.Color(0, 0, 204));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        laporanCis.setText("Laporan CIS");
        laporanCis.setIconReflection(new javax.swing.ImageIcon(getClass().getResource("/com/bpd/arsip/icon/LaporanCis.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        add(laporanCis, gridBagConstraints);

        laporanPengembalianBerkas.setText("Lap PengembalianBerkas");
        laporanPengembalianBerkas.setIconReflection(new javax.swing.ImageIcon(getClass().getResource("/com/bpd/arsip/icon/LaporanPengembalian.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
        add(laporanPengembalianBerkas, gridBagConstraints);

        laporanOpname.setText("Laporan Opname Berkas");
        laporanOpname.setIconReflection(new javax.swing.ImageIcon(getClass().getResource("/com/bpd/arsip/icon/LaporanOpnameBerkas.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 33, 6, 0);
        add(laporanOpname, gridBagConstraints);

        laporanIsiDus.setText("Laporan Isi Dus");
        laporanIsiDus.setIconReflection(new javax.swing.ImageIcon(getClass().getResource("/com/bpd/arsip/icon/LaporanIsiDus.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 33, 0, 0);
        add(laporanIsiDus, gridBagConstraints);

        laporanJatuhTempo.setText("Laporan Berkas Jatuh Tempo");
        laporanJatuhTempo.setIconReflection(new javax.swing.ImageIcon(getClass().getResource("/com/bpd/arsip/icon/LaporanJatuhTempo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 28, 6, 6);
        add(laporanJatuhTempo, gridBagConstraints);

        laporanPenerimaanBerkas.setText("Lap Penerimaan Berkas");
        laporanPenerimaanBerkas.setIconReflection(new javax.swing.ImageIcon(getClass().getResource("/com/bpd/arsip/icon/LaporanPenerimaan.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 28, 0, 6);
        add(laporanPenerimaanBerkas, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dany.swing.lib.button.ButtonIconGlass laporanCis;
    private dany.swing.lib.button.ButtonIconGlass laporanIsiDus;
    private dany.swing.lib.button.ButtonIconGlass laporanJatuhTempo;
    private dany.swing.lib.button.ButtonIconGlass laporanOpname;
    private dany.swing.lib.button.ButtonIconGlass laporanPenerimaanBerkas;
    private dany.swing.lib.button.ButtonIconGlass laporanPengembalianBerkas;
    // End of variables declaration//GEN-END:variables
}
