/*
 * Aplikasi pengarsipan untuk mengelola berkas kredit PLO dan KWU di Bank Jateng Purwokerto.
 * Aplikasi ini dibuat oleh Dany Candra Febrianto | Bank Jateng Purwokerto 2016
 * Aplikasi ini bebas di modifikasi dan di kembangkan.
 */
package com.bpd.arsip.view.panel;

import com.bpd.arsip.controller.LaporanIsiDusController;
import com.bpd.arsip.model.DusModel;
import com.bpd.arsip.model.PengarsipanModel;
import com.bpd.arsip.view.MainFrame;
import com.stripbandunk.jwidget.JDynamicTable;
import com.stripbandunk.jwidget.JPagination;
import com.stripbandunk.jwidget.model.DynamicTableModel;

/**
 *
 * @author Dany Candra
 */
public class PanelLaporanIsiDus extends javax.swing.JPanel {

    private final DusModel dusModel;
    private final PengarsipanModel pengarsipanModel;
    private final DynamicTableModel<DusModel> tableModelDus;
    private final DynamicTableModel<PengarsipanModel> tableModelPengarsipan;
    private final LaporanIsiDusController controller;
    private final int PAGE_SIZE = 20;
    private MainFrame mainFrame;

    /**
     * Creates new form PanelLaporanIsiDus
     */
    public PanelLaporanIsiDus() {

        dusModel = new DusModel();
        pengarsipanModel = new PengarsipanModel();
        controller = new LaporanIsiDusController();
        controller.setDusModel(dusModel);
        controller.setPengarsipanModel(pengarsipanModel);

        tableModelDus = new DynamicTableModel<>(DusModel.class);
        tableModelPengarsipan = new DynamicTableModel<>(PengarsipanModel.class);
        tableModelPengarsipan.setGroup("ttpengembalian");

        initComponents();

        tableDus.setDynamicModel(tableModelDus);
        tableBerkas.setDynamicModel(tableModelPengarsipan);

    }

    public MainFrame getMainFrame() {
        return mainFrame;
    }

    public void setMainFrame(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
    }

    public DynamicTableModel<PengarsipanModel> getTableModelPengarsipan() {
        return tableModelPengarsipan;
    }

    public JDynamicTable getTableBerkas() {
        return tableBerkas;
    }

    public DynamicTableModel<DusModel> getTableModelDus() {
        return tableModelDus;
    }

    public JPagination getjPagination() {
        return jPagination;
    }

    public JDynamicTable getTableDus() {
        return tableDus;
    }

    public JDynamicTable getTablePengembalianBerkas() {
        return tableBerkas;
    }

    public void loadTable() {
        controller.loadTableDus(PAGE_SIZE, this);
        tableModelPengarsipan.clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPortTransparan1 = new com.bpd.arsip.component.ViewPortTransparan();
        viewPortTransparan2 = new com.bpd.arsip.component.ViewPortTransparan();
        jPanelDus = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDus = new com.stripbandunk.jwidget.JDynamicTable();
        jPagination = new com.stripbandunk.jwidget.JPagination();
        buttonPerDus = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableBerkas = new com.stripbandunk.jwidget.JDynamicTable();

        viewPortTransparan1.setView(tableDus);

        viewPortTransparan2.setView(tableBerkas);

        setOpaque(false);

        jPanelDus.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Daftar Dus", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelDus.setOpaque(false);

        jScrollPane2.setViewport(viewPortTransparan1);

        tableDus.setForeground(new java.awt.Color(255, 255, 255));
        tableDus.setOpaque(false);
        tableDus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDusMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableDus);

        jPagination.setOpaque(false);
        jPagination.addPaginationListener(new com.stripbandunk.jwidget.listener.PaginationListener() {
            public void onPageChange(com.stripbandunk.jwidget.event.PaginationEvent evt) {
                jPaginationOnPageChange(evt);
            }
        });

        buttonPerDus.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonPerDus.setText("Cetak Per Dus");
        buttonPerDus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPerDusActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton3.setText("Cetak Cover Dus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDusLayout = new javax.swing.GroupLayout(jPanelDus);
        jPanelDus.setLayout(jPanelDusLayout);
        jPanelDusLayout.setHorizontalGroup(
            jPanelDusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPagination, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                    .addGroup(jPanelDusLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPerDus, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanelDusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDusLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelDusLayout.setVerticalGroup(
            jPanelDusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDusLayout.createSequentialGroup()
                .addGroup(jPanelDusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPerDus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(jPagination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelDusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDusLayout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(53, Short.MAX_VALUE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Daftar Dus", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setViewport(viewPortTransparan2);

        tableBerkas.setForeground(new java.awt.Color(255, 255, 255));
        tableBerkas.setOpaque(false);
        jScrollPane3.setViewportView(tableBerkas);

        jPanel2.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableDusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDusMouseClicked
        // TODO add your handling code here:
        controller.loadTableBerkasByIdDus(this);
    }//GEN-LAST:event_tableDusMouseClicked

    private void jPaginationOnPageChange(com.stripbandunk.jwidget.event.PaginationEvent evt) {//GEN-FIRST:event_jPaginationOnPageChange
        // TODO add your handling code here:
        final int skip = (evt.getCurrentPage() - 1) * evt.getPageSize();
        final int max = evt.getPageSize();
        controller.onPageChangeTableDus(skip, max, this);
    }//GEN-LAST:event_jPaginationOnPageChange

    private void buttonPerDusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPerDusActionPerformed
        // TODO add your handling code here:
        controller.cetakDaftarPerDus(this);
    }//GEN-LAST:event_buttonPerDusActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        controller.cetakDaftarCoverDus(this);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPerDus;
    private javax.swing.JButton jButton3;
    private com.stripbandunk.jwidget.JPagination jPagination;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDus;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.stripbandunk.jwidget.JDynamicTable tableBerkas;
    private com.stripbandunk.jwidget.JDynamicTable tableDus;
    private com.bpd.arsip.component.ViewPortTransparan viewPortTransparan1;
    private com.bpd.arsip.component.ViewPortTransparan viewPortTransparan2;
    // End of variables declaration//GEN-END:variables
}
