/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bpd.arsip.view.panel;

import dany.swing.lib.button.ButtonIconGlass;
import java.awt.event.ActionListener;

/**
 *
 * @author Dany
 */
public class PanelMenuPengaturan extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuUser
     */
    public PanelMenuPengaturan() {
        initComponents();
    }

    public void addListenerMenuPengaturanPenyimpananBerkas(ActionListener listener) {
        penyimpananBerkas.addActionListener(listener);
    }

    public void addListenerMenuPengaturanDaftarInstansi(ActionListener listener) {
        daftarInstansi.addActionListener(listener);
    }

    public void addListenerMenuPengaturanGantiPassword(ActionListener listener) {
        gantiPassword.addActionListener(listener);
    }

    public void addListenerMenuPengaturanPejabatBank(ActionListener listener) {
        pejabatBank.addActionListener(listener);
    }

    public void addListenerMenuPengaturanDaftarUser(ActionListener listener) {
        daftarUser.addActionListener(listener);
    }

    public ButtonIconGlass getDaftarUser() {
        return daftarUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        penyimpananBerkas = new dany.swing.lib.button.ButtonIconGlass();
        pejabatBank = new dany.swing.lib.button.ButtonIconGlass();
        daftarInstansi = new dany.swing.lib.button.ButtonIconGlass();
        gantiPassword = new dany.swing.lib.button.ButtonIconGlass();
        daftarUser = new dany.swing.lib.button.ButtonIconGlass();

        setBackground(new java.awt.Color(0, 51, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        penyimpananBerkas.setText("Penyimpanan Berkas");
        penyimpananBerkas.setIconReflection(new javax.swing.ImageIcon(getClass().getResource("/com/bpd/arsip/icon/PenyimpananBerkas.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 42, 0, 0);
        add(penyimpananBerkas, gridBagConstraints);

        pejabatBank.setText("Pejabat Bank");
        pejabatBank.setIconReflection(new javax.swing.ImageIcon(getClass().getResource("/com/bpd/arsip/icon/PejabatBank.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 70, 0, 0);
        add(pejabatBank, gridBagConstraints);

        daftarInstansi.setText("Daftar Instansi");
        daftarInstansi.setIconReflection(new javax.swing.ImageIcon(getClass().getResource("/com/bpd/arsip/icon/DaftarInstansi.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 42, 16, 0);
        add(daftarInstansi, gridBagConstraints);

        gantiPassword.setText("Ganti Password");
        gantiPassword.setIconReflection(new javax.swing.ImageIcon(getClass().getResource("/com/bpd/arsip/icon/GantiPassword.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 70, 16, 0);
        add(gantiPassword, gridBagConstraints);

        daftarUser.setText("Daftar User");
        daftarUser.setIconReflection(new javax.swing.ImageIcon(getClass().getResource("/com/bpd/arsip/icon/DaftarUser.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 75, 0, 49);
        add(daftarUser, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dany.swing.lib.button.ButtonIconGlass daftarInstansi;
    private dany.swing.lib.button.ButtonIconGlass daftarUser;
    private dany.swing.lib.button.ButtonIconGlass gantiPassword;
    private dany.swing.lib.button.ButtonIconGlass pejabatBank;
    private dany.swing.lib.button.ButtonIconGlass penyimpananBerkas;
    // End of variables declaration//GEN-END:variables
}
