/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bpd.arsip.view.panel;

import com.bpd.arsip.component.CenterFrame;
import com.bpd.arsip.controller.PencarianController;
import com.bpd.arsip.model.BerkasModel;
import com.bpd.arsip.model.DebiturModel;
import com.bpd.arsip.model.PengarsipanModel;
import com.bpd.arsip.view.MainFrame;
import com.stripbandunk.jwidget.JDynamicTable;
import com.stripbandunk.jwidget.JPagination;
import com.stripbandunk.jwidget.model.DynamicTableModel;
import javax.swing.JDialog;
import javax.swing.JTextField;

/**
 *
 * @author Dany Candra
 */
public class PanelPencarianBerkas extends javax.swing.JPanel {

    private final PengarsipanModel pengarsipanModel;
    private final DebiturModel debiturModel;
    private final BerkasModel berkasModel;
    private final DynamicTableModel<PengarsipanModel> tableModel;
    private final DynamicTableModel<BerkasModel> tableModelBerkas;
    private final PencarianController controller;
    private final int PAGE_SIZE = 20;
    private MainFrame mainFrame;

    /**
     * Creates new form PanelInstansi
     */
    public PanelPencarianBerkas() {
        pengarsipanModel = new PengarsipanModel();
        debiturModel = new DebiturModel();
        berkasModel = new BerkasModel();

        controller = new PencarianController();
        controller.setPengarsipanModel(pengarsipanModel);
        controller.setDebiturModel(debiturModel);
        controller.setBerkasModel(berkasModel);

        tableModelBerkas = new DynamicTableModel<>(BerkasModel.class);
        tableModel = new DynamicTableModel<>(PengarsipanModel.class);

        tableModel.setGroup("ttpengembalian");

        initComponents();

        tablePengembalianBerkas.setDynamicModel(tableModel);
        tableBerkas.setDynamicModel(tableModelBerkas);

        CenterFrame.makeCenter(dialogDetail);

    }

    public JDialog getDialogDetail() {
        return dialogDetail;
    }

    public MainFrame getMainFrame() {
        return mainFrame;
    }

    public void setMainFrame(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
    }

    public DynamicTableModel<PengarsipanModel> getTableModel() {
        return tableModel;
    }

    public JDynamicTable getTablePengembalianBerkas() {
        return tablePengembalianBerkas;
    }

    public JPagination getjPagination() {
        return jPagination;
    }

    public JTextField getTextCIF() {
        return textCIF;
    }

    public JTextField getTextNama() {
        return textNama;
    }

    public void loadTable() {
        controller.reload(PAGE_SIZE, this);
        disbaleInput();
    }

    public void disbaleInput() {
        textCIF.setEnabled(false);
        textNama.setEnabled(false);
    }

    public JDynamicTable getTableBerkas() {
        return tableBerkas;
    }

    public DynamicTableModel<BerkasModel> getTableModelBerkas() {
        return tableModelBerkas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        viewPortTransparan1 = new com.bpd.arsip.component.ViewPortTransparan();
        viewPortTransparan2 = new com.bpd.arsip.component.ViewPortTransparan();
        dialogDetail = new javax.swing.JDialog();
        panelGradient2 = new dany.swing.lib.panel.PanelGradient();
        labelWhite1 = new dany.swing.lib.label.LabelWhite();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableBerkas = new com.stripbandunk.jwidget.JDynamicTable();
        viewPortTransparan3 = new com.bpd.arsip.component.ViewPortTransparan();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePengembalianBerkas = new com.stripbandunk.jwidget.JDynamicTable();
        jPagination = new com.stripbandunk.jwidget.JPagination();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textCIF = new javax.swing.JTextField();
        buttonCek = new javax.swing.JButton();
        textNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        radioButtonCIF = new javax.swing.JRadioButton();
        radioButtonNama = new javax.swing.JRadioButton();
        buttonTandaTerima = new javax.swing.JButton();
        buttonCoverMap = new javax.swing.JButton();
        buttonDetail = new javax.swing.JButton();

        dialogDetail.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogDetail.setMinimumSize(new java.awt.Dimension(700, 300));
        dialogDetail.setModal(true);

        panelGradient2.setColorBottom(new java.awt.Color(0, 51, 153));

        labelWhite1.setText("DETAIL KELENGKAPAN BERKAS");
        labelWhite1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N

        jScrollPane4.setViewport(viewPortTransparan3);

        tableBerkas.setForeground(new java.awt.Color(255, 255, 255));
        tableBerkas.setOpaque(false);
        jScrollPane4.setViewportView(tableBerkas);

        javax.swing.GroupLayout panelGradient2Layout = new javax.swing.GroupLayout(panelGradient2);
        panelGradient2.setLayout(panelGradient2Layout);
        panelGradient2Layout.setHorizontalGroup(
            panelGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGradient2Layout.createSequentialGroup()
                        .addComponent(labelWhite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelGradient2Layout.setVerticalGroup(
            panelGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelWhite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addContainerGap())
        );

        dialogDetail.getContentPane().add(panelGradient2, java.awt.BorderLayout.CENTER);

        viewPortTransparan3.setView(tableBerkas);

        setBackground(new java.awt.Color(51, 51, 255));
        setOpaque(false);

        jScrollPane1.setViewport(viewPortTransparan1);

        tablePengembalianBerkas.setForeground(new java.awt.Color(255, 255, 255));
        tablePengembalianBerkas.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        tablePengembalianBerkas.setOpaque(false);
        jScrollPane1.setViewportView(tablePengembalianBerkas);

        jPagination.setOpaque(false);
        jPagination.addPaginationListener(new com.stripbandunk.jwidget.listener.PaginationListener() {
            public void onPageChange(com.stripbandunk.jwidget.event.PaginationEvent evt) {
                jPaginationOnPageChange(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Pencarian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MASUKAN CIF");

        textCIF.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        textCIF.setEnabled(false);
        textCIF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textCIFKeyReleased(evt);
            }
        });

        buttonCek.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonCek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bpd/arsip/icon/search.png"))); // NOI18N
        buttonCek.setText("Cari");
        buttonCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCekActionPerformed(evt);
            }
        });

        textNama.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        textNama.setEnabled(false);
        textNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textNamaKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MASUKAN NAMA");

        buttonGroup.add(radioButtonCIF);
        radioButtonCIF.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButtonCIFItemStateChanged(evt);
            }
        });
        radioButtonCIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonCIFActionPerformed(evt);
            }
        });

        buttonGroup.add(radioButtonNama);
        radioButtonNama.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButtonNamaItemStateChanged(evt);
            }
        });
        radioButtonNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonNamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textCIF)
                            .addComponent(textNama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioButtonCIF)
                            .addComponent(radioButtonNama)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonCek, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioButtonCIF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textCIF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioButtonNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCek, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        buttonTandaTerima.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonTandaTerima.setText("Cetak Tanda Terima");
        buttonTandaTerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTandaTerimaActionPerformed(evt);
            }
        });

        buttonCoverMap.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonCoverMap.setText("Cetak Cover Map");
        buttonCoverMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCoverMapActionPerformed(evt);
            }
        });

        buttonDetail.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonDetail.setText("Tampilkan Berkas");
        buttonDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonDetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCoverMap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonTandaTerima))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPagination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTandaTerima, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCoverMap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDetail))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPagination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonCoverMap, buttonDetail});

    }// </editor-fold>//GEN-END:initComponents

    private void textCIFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCIFKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            controller.search(textCIF.getText(), this);
        }
    }//GEN-LAST:event_textCIFKeyReleased

    private void jPaginationOnPageChange(com.stripbandunk.jwidget.event.PaginationEvent evt) {//GEN-FIRST:event_jPaginationOnPageChange
        // TODO add your handling code here:
        final int skip = (evt.getCurrentPage() - 1) * evt.getPageSize();
        final int max = evt.getPageSize();
        controller.onPageChange(skip, max, this);
    }//GEN-LAST:event_jPaginationOnPageChange

    private void buttonCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCekActionPerformed
        // TODO add your handling code here:
        if (radioButtonCIF.isSelected()) {
            controller.search(textCIF.getText(), this);
        } else if (radioButtonNama.isSelected()) {
            controller.searchByName(textNama.getText(), this);
        }

    }//GEN-LAST:event_buttonCekActionPerformed

    private void buttonCoverMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCoverMapActionPerformed
        // TODO add your handling code here:
        controller.cetakCover(this);
    }//GEN-LAST:event_buttonCoverMapActionPerformed

    private void buttonTandaTerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTandaTerimaActionPerformed
        // TODO add your handling code here:
        controller.cetakTandaTerima(this);
    }//GEN-LAST:event_buttonTandaTerimaActionPerformed

    private void textNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNamaKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            controller.searchByName(textNama.getText(), this);
        }
    }//GEN-LAST:event_textNamaKeyReleased

    private void radioButtonCIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonCIFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_radioButtonCIFActionPerformed

    private void radioButtonNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonNamaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_radioButtonNamaActionPerformed

    private void radioButtonCIFItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioButtonCIFItemStateChanged
        // TODO add your handling code here:
        textCIF.setEnabled(radioButtonCIF.isSelected());
        textNama.setText("");
    }//GEN-LAST:event_radioButtonCIFItemStateChanged

    private void radioButtonNamaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioButtonNamaItemStateChanged
        // TODO add your handling code here:
        textNama.setEnabled(radioButtonNama.isSelected());
        textCIF.setText("");
    }//GEN-LAST:event_radioButtonNamaItemStateChanged

    private void buttonDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDetailActionPerformed
        // TODO add your handling code here:
        controller.selectDebiturDetail(this);
    }//GEN-LAST:event_buttonDetailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCek;
    private javax.swing.JButton buttonCoverMap;
    private javax.swing.JButton buttonDetail;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton buttonTandaTerima;
    private javax.swing.JDialog dialogDetail;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.stripbandunk.jwidget.JPagination jPagination;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private dany.swing.lib.label.LabelWhite labelWhite1;
    private dany.swing.lib.panel.PanelGradient panelGradient2;
    private javax.swing.JRadioButton radioButtonCIF;
    private javax.swing.JRadioButton radioButtonNama;
    private com.stripbandunk.jwidget.JDynamicTable tableBerkas;
    private com.stripbandunk.jwidget.JDynamicTable tablePengembalianBerkas;
    private javax.swing.JTextField textCIF;
    private javax.swing.JTextField textNama;
    private com.bpd.arsip.component.ViewPortTransparan viewPortTransparan1;
    private com.bpd.arsip.component.ViewPortTransparan viewPortTransparan2;
    private com.bpd.arsip.component.ViewPortTransparan viewPortTransparan3;
    // End of variables declaration//GEN-END:variables
}
