/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bpd.arsip.view.dialog;

import com.bpd.arsip.component.CenterFrame;
import com.bpd.arsip.controller.PengembalianController;
import com.bpd.arsip.helper.list.PejabatListCellRender;
import com.bpd.arsip.model.PejabatModel;
import com.bpd.arsip.model.UserModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author Dany Candra
 */
public class DialogPengembalian extends javax.swing.JDialog {

    private PejabatModel pejabatModel;
    private UserModel userModel;
    private final PengembalianController controller;
    private final DefaultComboBoxModel<PejabatModel> comboPejabatModel;

    /**
     * Creates new form DialogPengembalian
     * @param pengembalianController
     */
    public DialogPengembalian(PengembalianController pengembalianController) {
        setModal(true);
        initComponents();
        CenterFrame.makeCenter(this);
        pejabatModel = new PejabatModel();
        this.controller=pengembalianController;
        controller.setPejabatModel(pejabatModel);
        comboPejabatModel = new DefaultComboBoxModel<>();
        comboPejabat.setModel(comboPejabatModel);
        comboPejabat.setRenderer(new PejabatListCellRender());
    }

    public PejabatModel getPejabatModel() {
        return pejabatModel;
    }

    public void setPejabatModel(PejabatModel pejabatModel) {
        this.pejabatModel = pejabatModel;
    }

    public UserModel getUserModel() {
        return userModel;
    }

    public void setUserModel(UserModel userModel) {
        this.userModel = userModel;
    }

    public DefaultComboBoxModel<PejabatModel> getComboPejabatModel() {
        return comboPejabatModel;
    }

    public JComboBox getComboPejabat() {
        return comboPejabat;
    }

    public JComboBox getComboAlasan() {
        return comboAlasan;
    }

    public void loadCombo() {
        controller.loadPejabatCombobox(this);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradient1 = new dany.swing.lib.panel.PanelGradient();
        jLabel1 = new javax.swing.JLabel();
        comboPejabat = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        comboAlasan = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelImageAlpha1 = new dany.swing.lib.panel.PanelImageAlpha();
        labelWhite1 = new dany.swing.lib.label.LabelWhite();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelGradient1.setColorBottom(new java.awt.Color(0, 0, 153));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PEJABAT PENGEMBALI");

        comboPejabat.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        comboPejabat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ALASAN PMGEMBALIAN");

        comboAlasan.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        comboAlasan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pelunasan", "Kredit Selesai" }));

        jButton1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        panelImageAlpha1.setAlpha(0.4F);
        panelImageAlpha1.setImageBackground(new javax.swing.ImageIcon(getClass().getResource("/com/bpd/arsip/icon/header.jpg"))); // NOI18N

        labelWhite1.setText("e'Arsip | Pengembalian Berkas");
        labelWhite1.setFont(new java.awt.Font("sansserif", 1, 28)); // NOI18N

        javax.swing.GroupLayout panelImageAlpha1Layout = new javax.swing.GroupLayout(panelImageAlpha1);
        panelImageAlpha1.setLayout(panelImageAlpha1Layout);
        panelImageAlpha1Layout.setHorizontalGroup(
            panelImageAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImageAlpha1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelWhite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelImageAlpha1Layout.setVerticalGroup(
            panelImageAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImageAlpha1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelWhite1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImageAlpha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGradient1Layout.createSequentialGroup()
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboAlasan, 0, 383, Short.MAX_VALUE)
                            .addComponent(comboPejabat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        panelGradient1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient1Layout.createSequentialGroup()
                .addComponent(panelImageAlpha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboAlasan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboPejabat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        getContentPane().add(panelGradient1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        controller.savePengembalian(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboAlasan;
    private javax.swing.JComboBox comboPejabat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private dany.swing.lib.label.LabelWhite labelWhite1;
    private dany.swing.lib.panel.PanelGradient panelGradient1;
    private dany.swing.lib.panel.PanelImageAlpha panelImageAlpha1;
    // End of variables declaration//GEN-END:variables
}
